// ⚠️ ARQUIVO GERADO — não edite à mão.
// Gerado por scripts/gen-operations.mjs a partir do schema central de endpoints
// (frontend/src/data/endpoints-schema.ts), a mesma fonte de /documentation,
// /api-docs, openapi.json, llms.txt e do Postman.
//
// Regenerar:  npm run gen:ops
//
// As operações escritas à mão no Wafly.node.ts têm PRECEDÊNCIA e não aparecem
// aqui: elas têm UX melhor (campos validados, unidades convertidas). Este
// arquivo cobre o resto da API para que nenhum endpoint fique inacessível pelo
// node.
//
// Endpoints cobertos aqui: 57

import type { INodeProperties } from 'n8n-workflow';

export interface GeneratedOperation {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  pathParams: string[];
  hasBody: boolean;
  isPartner: boolean;
}

export const GENERATED_OPERATIONS: Record<string, GeneratedOperation> = {
  'messageExtra:sendDocument': { method: 'POST', path: '/send-document/{type}', pathParams: ['type'], hasBody: true, isPartner: false },
  'messageExtra:sendContacts': { method: 'POST', path: '/send-contacts', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:pinMessage': { method: 'POST', path: '/pin-message', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendOptionList': { method: 'POST', path: '/send-option-list', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendGif': { method: 'POST', path: '/send-gif', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendPtv': { method: 'POST', path: '/send-ptv', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendEvent': { method: 'POST', path: '/send-event', pathParams: [], hasBody: true, isPartner: false },
  'groupExtra:groupInviteLink': { method: 'GET', path: '/group/invite-link', pathParams: [], hasBody: false, isPartner: false },
  'groupExtra:groupPhotoUrl': { method: 'POST', path: '/group/photo', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:listNewsletters': { method: 'GET', path: '/newsletter', pathParams: [], hasBody: false, isPartner: false },
  'newsletter:createNewsletter': { method: 'POST', path: '/create-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterMetadata': { method: 'GET', path: '/newsletter/metadata/{newsletterId}', pathParams: ['newsletterId'], hasBody: false, isPartner: false },
  'newsletter:followNewsletter': { method: 'PUT', path: '/follow-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:unfollowNewsletter': { method: 'PUT', path: '/unfollow-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterSettings': { method: 'POST', path: '/newsletter/settings/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:muteNewsletter': { method: 'PUT', path: '/mute-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:deleteNewsletter': { method: 'DELETE', path: '/delete-newsletter', pathParams: [], hasBody: false, isPartner: false },
  'newsletter:unmuteNewsletter': { method: 'PUT', path: '/unmute-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterPicture': { method: 'POST', path: '/update-newsletter-picture', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterName': { method: 'POST', path: '/update-newsletter-name', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterDescription': { method: 'POST', path: '/update-newsletter-description', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:searchNewsletter': { method: 'POST', path: '/search-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterAcceptAdminInvite': { method: 'POST', path: '/newsletter/accept-admin-invite/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:newsletterRemoveAdmin': { method: 'POST', path: '/newsletter/remove-admin/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:newsletterRevokeAdminInvite': { method: 'POST', path: '/newsletter/revoke-admin-invite/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:newsletterTransferOwnership': { method: 'POST', path: '/newsletter/transfer-ownership/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'instanceExtra:getQrCode': { method: 'GET', path: '/qr-code/image', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:passkeyChallenge': { method: 'GET', path: '/passkey-challenge', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:passkeyResponse': { method: 'POST', path: '/passkey-response', pathParams: [], hasBody: true, isPartner: false },
  'instanceExtra:pairingCode': { method: 'GET', path: '/pairing-code', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:pairingCodePost': { method: 'POST', path: '/pairing-code', pathParams: [], hasBody: true, isPartner: false },
  'instanceExtra:restartWithDisconnect': { method: 'POST', path: '/restart-with-disconnect', pathParams: [], hasBody: true, isPartner: false },
  'chat:listChats': { method: 'GET', path: '/chats', pathParams: [], hasBody: false, isPartner: false },
  'chat:modifyChat': { method: 'POST', path: '/modify-chat', pathParams: [], hasBody: true, isPartner: false },
  'chat:chatMetadata': { method: 'GET', path: '/chats/{phone}', pathParams: ['phone'], hasBody: false, isPartner: false },
  'community:listCommunities': { method: 'GET', path: '/communities', pathParams: [], hasBody: false, isPartner: false },
  'community:createCommunity': { method: 'POST', path: '/communities', pathParams: [], hasBody: true, isPartner: false },
  'community:linkCommunity': { method: 'POST', path: '/communities/link', pathParams: [], hasBody: true, isPartner: false },
  'community:unlinkCommunity': { method: 'POST', path: '/communities/unlink', pathParams: [], hasBody: true, isPartner: false },
  'community:communityMetadata': { method: 'GET', path: '/communities-metadata/{communityId}', pathParams: ['communityId'], hasBody: false, isPartner: false },
  'community:communitySettings': { method: 'POST', path: '/communities/settings', pathParams: [], hasBody: true, isPartner: false },
  'community:deleteCommunity': { method: 'DELETE', path: '/communities/{communityId}', pathParams: ['communityId'], hasBody: false, isPartner: false },
  'partner:partnerCreateInstance': { method: 'POST', path: '/external/instances', pathParams: [], hasBody: true, isPartner: true },
  'call:callConfigGet': { method: 'GET', path: '/call/config', pathParams: [], hasBody: false, isPartner: false },
  'call:callConfigSet': { method: 'PUT', path: '/call/config', pathParams: [], hasBody: true, isPartner: false },
  'call:callStart': { method: 'POST', path: '/call/start', pathParams: [], hasBody: true, isPartner: false },
  'call:callAccept': { method: 'POST', path: '/call/accept', pathParams: [], hasBody: true, isPartner: false },
  'call:callReject': { method: 'POST', path: '/call/reject', pathParams: [], hasBody: true, isPartner: false },
  'call:callTerminate': { method: 'POST', path: '/call/terminate', pathParams: [], hasBody: true, isPartner: false },
  'call:callPlay': { method: 'POST', path: '/call/play', pathParams: [], hasBody: true, isPartner: false },
  'call:callSay': { method: 'POST', path: '/call/say', pathParams: [], hasBody: true, isPartner: false },
  'call:callWebrtc': { method: 'POST', path: '/call/webrtc', pathParams: [], hasBody: true, isPartner: false },
  'call:callRecordStart': { method: 'POST', path: '/call/{callId}/record/start', pathParams: ['callId'], hasBody: true, isPartner: false },
  'call:callRecordStop': { method: 'POST', path: '/call/{callId}/record/stop', pathParams: ['callId'], hasBody: true, isPartner: false },
  'call:callRecording': { method: 'GET', path: '/call/{callId}/recording', pathParams: ['callId'], hasBody: false, isPartner: false },
  'call:callTranscriptGet': { method: 'GET', path: '/call/{callId}/transcript', pathParams: ['callId'], hasBody: false, isPartner: false },
  'call:callTranscriptPost': { method: 'POST', path: '/call/{callId}/transcript', pathParams: ['callId'], hasBody: true, isPartner: false },
};

export const GENERATED_RESOURCES: Array<{ name: string; value: string }> = [
  { name: 'Message (More)', value: 'messageExtra' },
  { name: 'Group (More)', value: 'groupExtra' },
  { name: 'Newsletter / Channel', value: 'newsletter' },
  { name: 'Instance (More)', value: 'instanceExtra' },
  { name: 'Chat', value: 'chat' },
  { name: 'Community', value: 'community' },
  { name: 'Partner', value: 'partner' },
  { name: 'Call (Beta)', value: 'call' },
];

export const generatedProperties: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['messageExtra'] } },
    options: [
      { name: 'Enviar documento', value: 'sendDocument', action: 'Enviar documento' },
      { name: 'Enviar contato', value: 'sendContacts', action: 'Enviar contato' },
      { name: 'Fixar mensagem', value: 'pinMessage', action: 'Fixar mensagem' },
      { name: 'Enviar lista de opções', value: 'sendOptionList', action: 'Enviar lista de opções' },
      { name: 'Enviar GIF', value: 'sendGif', action: 'Enviar GIF' },
      { name: 'Enviar vídeo redondo (PTV)', value: 'sendPtv', action: 'Enviar vídeo redondo (PTV)' },
      { name: 'Enviar evento', value: 'sendEvent', action: 'Enviar evento' },
    ],
    default: 'sendDocument',
  },
  {
    displayName: 'Type',
    name: 'gp_type',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['messageExtra'], operation: ['sendDocument'] } },
    description: 'Valor de {type} na rota',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['messageExtra'], operation: ['sendDocument', 'sendContacts', 'pinMessage', 'sendOptionList', 'sendGif', 'sendPtv', 'sendEvent'] } },
    description: 'Corpo da requisição. Campos esperados por operação: sendContacts → contacts | pinMessage → phone*, messageId*, messageAction*, pinMessageDuration*, sender | sendOptionList → optionList* | sendEvent → event*',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['groupExtra'] } },
    options: [
      { name: 'Obter link de convite', value: 'groupInviteLink', action: 'Obter link de convite' },
      { name: 'Atualizar foto do grupo (por URL)', value: 'groupPhotoUrl', action: 'Atualizar foto do grupo (por URL)' },
    ],
    default: 'groupInviteLink',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['groupExtra'], operation: ['groupPhotoUrl'] } },
    description: 'Corpo da requisição. Campos esperados por operação: ',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['newsletter'] } },
    options: [
      { name: 'Listar newsletters', value: 'listNewsletters', action: 'Listar newsletters' },
      { name: 'Criar newsletter', value: 'createNewsletter', action: 'Criar newsletter' },
      { name: 'Metadados da newsletter', value: 'newsletterMetadata', action: 'Metadados da newsletter' },
      { name: 'Seguir newsletter', value: 'followNewsletter', action: 'Seguir newsletter' },
      { name: 'Deixar de seguir newsletter', value: 'unfollowNewsletter', action: 'Deixar de seguir newsletter' },
      { name: 'Configurações da newsletter', value: 'newsletterSettings', action: 'Configurações da newsletter' },
      { name: 'Silenciar newsletter', value: 'muteNewsletter', action: 'Silenciar newsletter' },
      { name: 'Deletar newsletter', value: 'deleteNewsletter', action: 'Deletar newsletter' },
      { name: 'Reativar som da newsletter', value: 'unmuteNewsletter', action: 'Reativar som da newsletter' },
      { name: 'Atualizar imagem da newsletter', value: 'updateNewsletterPicture', action: 'Atualizar imagem da newsletter' },
      { name: 'Alterar nome da newsletter', value: 'updateNewsletterName', action: 'Alterar nome da newsletter' },
      { name: 'Alterar descrição da newsletter', value: 'updateNewsletterDescription', action: 'Alterar descrição da newsletter' },
      { name: 'Buscar newsletters', value: 'searchNewsletter', action: 'Buscar newsletters' },
      { name: 'Aceitar convite de admin', value: 'newsletterAcceptAdminInvite', action: 'Aceitar convite de admin' },
      { name: 'Remover administrador da newsletter', value: 'newsletterRemoveAdmin', action: 'Remover administrador da newsletter' },
      { name: 'Revogar convite de admin', value: 'newsletterRevokeAdminInvite', action: 'Revogar convite de admin' },
      { name: 'Transferir propriedade da newsletter', value: 'newsletterTransferOwnership', action: 'Transferir propriedade da newsletter' },
    ],
    default: 'listNewsletters',
  },
  {
    displayName: 'Newsletter Id',
    name: 'gp_newsletterId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['newsletter'], operation: ['newsletterMetadata', 'newsletterSettings', 'newsletterAcceptAdminInvite', 'newsletterRemoveAdmin', 'newsletterRevokeAdminInvite', 'newsletterTransferOwnership'] } },
    description: 'Valor de {newsletterId} na rota',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['newsletter'], operation: ['createNewsletter', 'followNewsletter', 'unfollowNewsletter', 'newsletterSettings', 'muteNewsletter', 'unmuteNewsletter', 'updateNewsletterPicture', 'updateNewsletterName', 'updateNewsletterDescription', 'searchNewsletter', 'newsletterAcceptAdminInvite', 'newsletterRemoveAdmin', 'newsletterRevokeAdminInvite', 'newsletterTransferOwnership'] } },
    description: 'Corpo da requisição. Campos esperados por operação: newsletterSettings → reactionCodes | searchNewsletter → view, filters',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['instanceExtra'] } },
    options: [
      { name: 'QR Code para conexão', value: 'getQrCode', action: 'QR Code para conexão' },
      { name: 'Desafio de passkey (WebAuthn)', value: 'passkeyChallenge', action: 'Desafio de passkey (WebAuthn)' },
      { name: 'Enviar assinatura de passkey', value: 'passkeyResponse', action: 'Enviar assinatura de passkey' },
      { name: 'Código de emparelhamento (GET)', value: 'pairingCode', action: 'Código de emparelhamento (GET)' },
      { name: 'Código de emparelhamento (POST)', value: 'pairingCodePost', action: 'Código de emparelhamento (POST)' },
      { name: 'Reiniciar com desconexão', value: 'restartWithDisconnect', action: 'Reiniciar com desconexão' },
    ],
    default: 'getQrCode',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['instanceExtra'], operation: ['passkeyResponse', 'pairingCodePost', 'restartWithDisconnect'] } },
    description: 'Corpo da requisição. Campos esperados por operação: passkeyResponse → phones* | pairingCodePost → connected | restartWithDisconnect → connected',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['chat'] } },
    options: [
      { name: 'Listar conversas', value: 'listChats', action: 'Listar conversas' },
      { name: 'Marcar chat como lido/não lido', value: 'modifyChat', action: 'Marcar chat como lido/não lido' },
      { name: 'Metadados de um chat', value: 'chatMetadata', action: 'Metadados de um chat' },
    ],
    default: 'listChats',
  },
  {
    displayName: 'Phone',
    name: 'gp_phone',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['chat'], operation: ['chatMetadata'] } },
    description: 'Valor de {phone} na rota',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['chat'], operation: ['modifyChat'] } },
    description: 'Corpo da requisição. Campos esperados por operação: modifyChat → phone*, action*',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['community'] } },
    options: [
      { name: 'Listar comunidades', value: 'listCommunities', action: 'Listar comunidades' },
      { name: 'Criar comunidade', value: 'createCommunity', action: 'Criar comunidade' },
      { name: 'Vincular grupos à comunidade', value: 'linkCommunity', action: 'Vincular grupos à comunidade' },
      { name: 'Desvincular grupos da comunidade', value: 'unlinkCommunity', action: 'Desvincular grupos da comunidade' },
      { name: 'Metadados da comunidade', value: 'communityMetadata', action: 'Metadados da comunidade' },
      { name: 'Configurações da comunidade', value: 'communitySettings', action: 'Configurações da comunidade' },
      { name: 'Desativar comunidade', value: 'deleteCommunity', action: 'Desativar comunidade' },
    ],
    default: 'listCommunities',
  },
  {
    displayName: 'Community Id',
    name: 'gp_communityId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['community'], operation: ['communityMetadata', 'deleteCommunity'] } },
    description: 'Valor de {communityId} na rota',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['community'], operation: ['createCommunity', 'linkCommunity', 'unlinkCommunity', 'communitySettings'] } },
    description: 'Corpo da requisição. Campos esperados por operação: communitySettings → whoCanAddNewGroups*',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['partner'] } },
    options: [
      { name: 'Criar instância (parceiro)', value: 'partnerCreateInstance', action: 'Criar instância (parceiro)' },
    ],
    default: 'partnerCreateInstance',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['partner'], operation: ['partnerCreateInstance'] } },
    description: 'Corpo da requisição. Campos esperados por operação: partnerCreateInstance → receivedCallbackUrl, deliveryCallbackUrl, disconnectedCallbackUrl, messageStatusCallbackUrl',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['call'] } },
    options: [
      { name: 'Ver configuração de chamadas', value: 'callConfigGet', action: 'Ver configuração de chamadas' },
      { name: 'Configurar chamadas recebidas', value: 'callConfigSet', action: 'Configurar chamadas recebidas' },
      { name: 'Iniciar chamada', value: 'callStart', action: 'Iniciar chamada' },
      { name: 'Atender chamada', value: 'callAccept', action: 'Atender chamada' },
      { name: 'Recusar chamada', value: 'callReject', action: 'Recusar chamada' },
      { name: 'Encerrar chamada', value: 'callTerminate', action: 'Encerrar chamada' },
      { name: 'Tocar áudio na chamada', value: 'callPlay', action: 'Tocar áudio na chamada' },
      { name: 'Falar texto na chamada (TTS)', value: 'callSay', action: 'Falar texto na chamada (TTS)' },
      { name: 'Ponte WebRTC', value: 'callWebrtc', action: 'Ponte WebRTC' },
      { name: 'Iniciar gravação', value: 'callRecordStart', action: 'Iniciar gravação' },
      { name: 'Parar gravação', value: 'callRecordStop', action: 'Parar gravação' },
      { name: 'Baixar gravação', value: 'callRecording', action: 'Baixar gravação' },
      { name: 'Ver transcrição', value: 'callTranscriptGet', action: 'Ver transcrição' },
      { name: 'Anexar transcrição', value: 'callTranscriptPost', action: 'Anexar transcrição' },
    ],
    default: 'callConfigGet',
  },
  {
    displayName: 'Call Id',
    name: 'gp_callId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['call'], operation: ['callRecordStart', 'callRecordStop', 'callRecording', 'callTranscriptGet', 'callTranscriptPost'] } },
    description: 'Valor de {callId} na rota',
  },
  {
    displayName: 'Body (JSON)',
    name: 'gp_body',
    type: 'json',
    default: '{}',
    displayOptions: { show: { resource: ['call'], operation: ['callConfigSet', 'callStart', 'callAccept', 'callReject', 'callTerminate', 'callPlay', 'callSay', 'callWebrtc', 'callRecordStart', 'callRecordStop', 'callTranscriptPost'] } },
    description: 'Corpo da requisição. Campos esperados por operação: callConfigSet → onIncoming*, mp3, ai, human | callStart → phone*, video, mp3Url, mp3Base64, hangupAfter | callPlay → base64, hangupAfter | callSay → voiceId, hangupAfter | callRecordStart → segments* | callRecordStop → segments* | callTranscriptPost → segments*',
  },
];
