// ⚠️ GENERATED FILE — do not edit by hand.
// Generated by scripts/gen-operations.mjs from the central endpoint schema
// (frontend/src/data/endpoints-schema.ts), the same source behind
// /documentation, /api-docs, openapi.json, llms.txt and the Postman collection.
//
// To regenerate:  npm run gen:ops
//
// The hand-written operations in Wafly.node.ts take PRECEDENCE and do not show
// up here: they have better UX (validated fields, converted units). This file
// covers the rest of the API so that no endpoint is unreachable from the node.
//
// Endpoints covered here: 57

export interface GeneratedOperation {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  pathParams: string[];
  hasBody: boolean;
  isPartner: boolean;
}

export const GENERATED_OPERATIONS: Record<string, GeneratedOperation> = {
  'messageExtra:pinMessage': { method: 'POST', path: '/pin-message', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendContacts': { method: 'POST', path: '/send-contacts', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendDocument': { method: 'POST', path: '/send-document/{type}', pathParams: ['type'], hasBody: true, isPartner: false },
  'messageExtra:sendEvent': { method: 'POST', path: '/send-event', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendGif': { method: 'POST', path: '/send-gif', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendOptionList': { method: 'POST', path: '/send-option-list', pathParams: [], hasBody: true, isPartner: false },
  'messageExtra:sendPtv': { method: 'POST', path: '/send-ptv', pathParams: [], hasBody: true, isPartner: false },
  'groupExtra:groupInviteLink': { method: 'GET', path: '/group/invite-link', pathParams: [], hasBody: false, isPartner: false },
  'groupExtra:groupPhotoUrl': { method: 'POST', path: '/group/photo', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterAcceptAdminInvite': { method: 'POST', path: '/newsletter/accept-admin-invite/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:createNewsletter': { method: 'POST', path: '/create-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:deleteNewsletter': { method: 'DELETE', path: '/delete-newsletter', pathParams: [], hasBody: false, isPartner: false },
  'newsletter:followNewsletter': { method: 'PUT', path: '/follow-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterMetadata': { method: 'GET', path: '/newsletter/metadata/{newsletterId}', pathParams: ['newsletterId'], hasBody: false, isPartner: false },
  'newsletter:listNewsletters': { method: 'GET', path: '/newsletter', pathParams: [], hasBody: false, isPartner: false },
  'newsletter:muteNewsletter': { method: 'PUT', path: '/mute-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterRemoveAdmin': { method: 'POST', path: '/newsletter/remove-admin/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:newsletterRevokeAdminInvite': { method: 'POST', path: '/newsletter/revoke-admin-invite/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:searchNewsletter': { method: 'POST', path: '/search-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterTransferOwnership': { method: 'POST', path: '/newsletter/transfer-ownership/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'newsletter:unfollowNewsletter': { method: 'PUT', path: '/unfollow-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:unmuteNewsletter': { method: 'PUT', path: '/unmute-newsletter', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterDescription': { method: 'POST', path: '/update-newsletter-description', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterName': { method: 'POST', path: '/update-newsletter-name', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:updateNewsletterPicture': { method: 'POST', path: '/update-newsletter-picture', pathParams: [], hasBody: true, isPartner: false },
  'newsletter:newsletterSettings': { method: 'POST', path: '/newsletter/settings/{newsletterId}', pathParams: ['newsletterId'], hasBody: true, isPartner: false },
  'instanceExtra:pairingCodePost': { method: 'POST', path: '/pairing-code', pathParams: [], hasBody: true, isPartner: false },
  'instanceExtra:pairingCode': { method: 'GET', path: '/pairing-code', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:passkeyChallenge': { method: 'GET', path: '/passkey-challenge', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:getQrCode': { method: 'GET', path: '/qr-code/image', pathParams: [], hasBody: false, isPartner: false },
  'instanceExtra:restartWithDisconnect': { method: 'POST', path: '/restart-with-disconnect', pathParams: [], hasBody: true, isPartner: false },
  'instanceExtra:passkeyResponse': { method: 'POST', path: '/passkey-response', pathParams: [], hasBody: true, isPartner: false },
  'chat:chatMetadata': { method: 'GET', path: '/chats/{phone}', pathParams: ['phone'], hasBody: false, isPartner: false },
  'chat:listChats': { method: 'GET', path: '/chats', pathParams: [], hasBody: false, isPartner: false },
  'chat:modifyChat': { method: 'POST', path: '/modify-chat', pathParams: [], hasBody: true, isPartner: false },
  'community:createCommunity': { method: 'POST', path: '/communities', pathParams: [], hasBody: true, isPartner: false },
  'community:deleteCommunity': { method: 'DELETE', path: '/communities/{communityId}', pathParams: ['communityId'], hasBody: false, isPartner: false },
  'community:communityMetadata': { method: 'GET', path: '/communities-metadata/{communityId}', pathParams: ['communityId'], hasBody: false, isPartner: false },
  'community:linkCommunity': { method: 'POST', path: '/communities/link', pathParams: [], hasBody: true, isPartner: false },
  'community:listCommunities': { method: 'GET', path: '/communities', pathParams: [], hasBody: false, isPartner: false },
  'community:unlinkCommunity': { method: 'POST', path: '/communities/unlink', pathParams: [], hasBody: true, isPartner: false },
  'community:communitySettings': { method: 'POST', path: '/communities/settings', pathParams: [], hasBody: true, isPartner: false },
  'partner:partnerCreateInstance': { method: 'POST', path: '/external/instances', pathParams: [], hasBody: true, isPartner: true },
  'call:callAccept': { method: 'POST', path: '/call/accept', pathParams: [], hasBody: true, isPartner: false },
  'call:callTranscriptPost': { method: 'POST', path: '/call/{callId}/transcript', pathParams: ['callId'], hasBody: true, isPartner: false },
  'call:callRecording': { method: 'GET', path: '/call/{callId}/recording', pathParams: ['callId'], hasBody: false, isPartner: false },
  'call:callConfigGet': { method: 'GET', path: '/call/config', pathParams: [], hasBody: false, isPartner: false },
  'call:callTranscriptGet': { method: 'GET', path: '/call/{callId}/transcript', pathParams: ['callId'], hasBody: false, isPartner: false },
  'call:callPlay': { method: 'POST', path: '/call/play', pathParams: [], hasBody: true, isPartner: false },
  'call:callReject': { method: 'POST', path: '/call/reject', pathParams: [], hasBody: true, isPartner: false },
  'call:callConfigSet': { method: 'PUT', path: '/call/config', pathParams: [], hasBody: true, isPartner: false },
  'call:callSay': { method: 'POST', path: '/call/say', pathParams: [], hasBody: true, isPartner: false },
  'call:callStart': { method: 'POST', path: '/call/start', pathParams: [], hasBody: true, isPartner: false },
  'call:callRecordStart': { method: 'POST', path: '/call/{callId}/record/start', pathParams: ['callId'], hasBody: true, isPartner: false },
  'call:callRecordStop': { method: 'POST', path: '/call/{callId}/record/stop', pathParams: ['callId'], hasBody: true, isPartner: false },
  'call:callTerminate': { method: 'POST', path: '/call/terminate', pathParams: [], hasBody: true, isPartner: false },
  'call:callWebrtc': { method: 'POST', path: '/call/webrtc', pathParams: [], hasBody: true, isPartner: false },
};
